[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api1/*"
  to = "https://www.mmobomb.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
